name: aoc-2022

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
      working-directory: ./aoc/aoc-2022
    - name: Run tests
      run: cd aoc/aoc-2022; cargo test --verbose
      working-directory: ./aoc/aoc-2022
